### ISSUE TITLE
raise RuntimeError("Cannot add middleware after an application has started")

### ISSUE THREAD

**Issue by jonra1993** [codemation/easyauth#98]
Thanks in advance for this tool, it is something I was looking for some time age. I was trying to initialize EasyAuthClient on new fastapi lifespan like this 

```
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    await EasyAuthClient.create(
        app,
        token_server='0.0.0.0',
        token_server_port=8090,
        auth_secret='abcd1234',
        default_permissions={'groups': ['users']}
    )
    print("startup fastapi")
    yield
    # shutdown
```

and I get this message error 
<img width="797" alt="image" src="https://user-images.githubusercontent.com/23468720/233750928-38a93cab-fb5d-4d7a-acf2-e053f7800dd5.png">

Do you have any idea how to run EasyAuthClient in lifespan also there is a way to use client as depends?

**Comment by codemation** [comment]
Using client as Depends is not an option explicitly right now. 

Creating a client is no longer required inside an event loop or supported after an FastAPI app has started due to changes in latest releases of FastAPI. See the latest example in docs and readme for latest usage. If you referenced the medium post, I still need to update that.

**Comment by jonra1993** [comment]
Thanks for the information @codemation
